pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = "AKIAVIMAPNUDABOBKWGC"
        AWS_SECRET_ACCESS_KEY = "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"
        AWS_DEFAULT_REGION = "ap-south-1"
    }
    stages {
        stage("Create an EKS Cluster") {
            steps {
                script {
                    dir('part2-cluster-from-terraform-and-jenkins/terraform-for-cluster') {
                        sh "terraform destroy"
                    }
                }
            }
        }
     
    }
}
